RBAC
spring-cloud/spring-cloud-dataflow-server-kubernetes pull request #242
Opened 2017-12-13 15:56 UTC by viniciusccarvalho

Fixes issues on deployer actually : https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/162

2017-12-14 15:12 UTC, sabbyanandan commented
Hi, @trisberg: When you get a chance, it'd be great if you can weigh-in on the proposed changes.

2017-12-20 16:45 UTC, trisberg commented
I'm getting a merge conflict on the docs that I'm not entirely sure how to resolve, could you rebase the PR?

2017-12-20 17:25 UTC, viniciusccarvalho commented
@trisberg just fixed it

2017-12-20 19:15 UTC, trisberg requested changes
Other than the doc changes and minor formatting issues LGTM, works, tried simple stream and task

2017-12-20 19:15 UTC, trisberg commented on spring-cloud-dataflow-server-kubernetes-docs/src/main/asciidoc/getting-started.adoc
> +=======
Formatting is off starting here

2017-12-20 19:15 UTC, trisberg commented on spring-cloud-dataflow-server-kubernetes-docs/src/main/asciidoc/getting-started.adoc
> +$ kubectl create -f src/kubernetes/server/server-rolebindings.yaml
file name is `server-rolebinding.yaml`

2017-12-20 19:15 UTC, trisberg commented on src/kubernetes/server/server-roles.yaml
> +    resources: ["services", "pods","replicationcontrollers"]
nit-pick: space after comma

2017-12-20 19:15 UTC, trisberg commented on src/kubernetes/server/server-roles.yaml
> +    resources: ["deployments", "replicasets","jobs"]
another space after comma

2017-12-20 19:51 UTC, trisberg commented
Updated to use BUILD-SNAPSHOT versions and getting a failure when deploying ticktock stream

```
2017-12-20 19:30:39.965 ERROR 1 --- [p-nio-80-exec-6] o.s.c.d.s.s.AppDeployerStreamDeployer    : Exception when deploying the app [stream name = ticktock, application name = log, application properties = {spring.metrics.export.triggers.application.includes=integration**, spring.cloud.dataflow.stream.app.label=log, spring.cloud.stream.metrics.key=ticktock.log.${spring.cloud.application.guid}, spring.cloud.stream.bindings.input.group=ticktock, spring.cloud.stream.metrics.properties=spring.application.name,spring.application.index,spring.cloud.application.*,spring.cloud.dataflow.*, spring.cloud.stream.bindings.applicationMetrics.destination=metrics, spring.cloud.dataflow.stream.name=ticktock, spring.cloud.dataflow.stream.app.type=sink, spring.cloud.stream.bindings.input.destination=ticktock.time}: Create StatefulSet failed. response code 403, message Forbidden
```

2017-12-20 20:47 UTC, trisberg commented
This configuration seems to work with StatefulSets:

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: scdf-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "replicationcontrollers", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
  - apiGroups: ["extensions"]
    resources: ["deployments", "replicasets", "jobs"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
```

2017-12-20 22:48 UTC, viniciusccarvalho commented
Just squashed all the commits @trisberg let me know if it addresses all issues

2017-12-21 14:29 UTC, trisberg commented
LGTM, merging ...

2017-12-21 14:30 UTC, trisberg commented
Merged as commit 9a568b153c49e65cb2e04c09a03ca7c3011524bf

2017-12-21 14:30 UTC, closed without merging